Add debug step to list output directory

diff --git a/.github/workflows/TWRP-Recovery-Builder.yml b/.github/workflows/TWRP-Recovery-Builder.yml
--- a/.github/workflows/TWRP-Recovery-Builder.yml
+++ b/.github/workflows/TWRP-Recovery-Builder.yml
@@ -149,7 +149,6 @@ jobs:
           lunch ${{ env.DEVICE_MAKEFILE }}-eng && make clean && make ${{ github.event.inputs.BUILD_TARGET }}image -j$(nproc --all)
           echo "Done building your ${{ github.event.inputs.BUILD_TARGET }}.img"
       - name: Set Build Date
-        # Output will be use in Release
         run: |
           echo "BUILD_DATE=$(date +%Y%m%d)" >> $GITHUB_ENV
           DEVICE_TREE_URL="${{ github.event.inputs.DEVICE_TREE }}"
@@ -157,17 +156,22 @@ jobs:
             DEVICE_TREE_URL="${DEVICE_TREE_URL%.git}"
           fi
           echo "DEVICE_TREE_URL=${DEVICE_TREE_URL}" >> $GITHUB_ENV
+      - name: Debug output files
+        run: |
+          cd workspace
+          echo "=== Directory listing ==="
+          ls -la out/target/product/${{ github.event.inputs.DEVICE_NAME }}/ || echo "DIR NOT FOUND"
       - name: Check if Recovery Exist
         run: |
           cd workspace
           if [ -f out/target/product/${{ github.event.inputs.DEVICE_NAME }}/recovery.img ]; then
             echo "RECOVERY_TYPE=recovery" >> $GITHUB_ENV
             echo "recovery.img file found!"
-            echo "MD5_IMG=$(md5sum out/target/product/${{ github.event.inputs.DEVICE_NAME }}/${{ github.event.inputs.BUILD_TARGET }}.img | cut -d ' ' -f 1)" >> $GITHUB_ENV
+            echo "MD5_IMG=$(md5sum out/target/product/${{ github.event.inputs.DEVICE_NAME }}/recovery.img | cut -d ' ' -f 1)" >> $GITHUB_ENV
           elif [ -f out/target/product/${{ github.event.inputs.DEVICE_NAME }}/boot.img ]; then
             echo "RECOVERY_TYPE=boot" >> $GITHUB_ENV
             echo "boot.img file found!"
-            echo "MD5_IMG=$(md5sum out/target/product/${{ github.event.inputs.DEVICE_NAME }}/${{ github.event.inputs.BUILD_TARGET }}.img | cut -d ' ' -f 1)" >> $GITHUB_ENV
+            echo "MD5_IMG=$(md5sum out/target/product/${{ github.event.inputs.DEVICE_NAME }}/boot.img | cut -d ' ' -f 1)" >> $GITHUB_ENV
           elif [ -f out/target/product/${{ github.event.inputs.DEVICE_NAME }}/vendor_boot.img ]; then
             echo "RECOVERY_TYPE=vendor_boot" >> $GITHUB_ENV
             echo "vendor_boot.img file found!"
